### PR TITLE
Add link to github repo in website footer

### LINKED ISSUE #127: Add direct link to Github?
Some projects have a direct link to their source code repos on their website.

For example directly in the Menu or in the footer section.

### PR DESCRIPTION
**Pull request by toby63**
Signed-off-by: Tobias Gerold <tobias@g3ro.eu>

Fixes #127.

### CODE REVIEW

**Comment by Kissaki** [comment]
AFAIR we already had limited space issues in the menu before. How does this handle adding yet another main menu item?

**Comment by Krzmbrzl** [comment]
The current website seems to use a responsive design were it will wrap the menu if there is not enough space left :point_up:

**Comment by toby63** [comment]
@Kissaki: It seems to me that this is a specific problem to your website design.
To centralised and too big and long mumble banner.

**Comment by Kissaki** [comment]
> 
> 
> @Kissaki: It seems to me that this is a specific problem to your website design.
> Too centralised and too big and long mumble banner.

I do not think this is my design.

**Comment by Kissaki** [comment]
> 
> 
> The current website seems to use a responsive design were it will wrap the menu if there is not enough space left ☝️

Making it two nav lines instead of one, wrapping one entry to the second line?

I think this is a very important layout change that should be mentioned in the commit and PR description.

**Comment by Krzmbrzl** [comment]
> Making it two nav lines instead of one, wrapping one entry to the second line?

Yes

> I think this is a very important layout change that should be mentioned in the commit and PR description. Something that should be decided upon consciously.

This is not (necessarily) introduced by this PR though. That's already the case. Just resize your browser window with the website open. Thus these changes only trigger a second nav line to be shown on a screen that is too small for making it a single nav line :shrug:

**Comment by toby63** [comment]
What about two things:
1. A Layout change? It could be wider.
2. A drop-down menu? (Things like "Source Code" and maybe others like "Contact" could be under "About" for example.

**Comment by Krzmbrzl** [comment]
A dropdown menu in general might be worth considering. It does have the disadvantage that this would basically mean that the site is only usable with JavaScript enabled.

**Comment by toby63** [comment]
> It does have the disadvantage that this would basically mean that the site is only usable with JavaScript enabled.

Afaik it is possible to have drop-down menus with html and css.

**Comment by Krzmbrzl** [comment]
Next question would be: How do we tell Hugo to do that?

**Comment by toby63** [comment]
https://discourse.gohugo.io/t/how-to-create-multilevel-dropdown-menu-in-hugo/18373/5

**Comment by Kissaki** [comment]
> Next question would be: How do we tell Hugo to do that?

You men a dropdown? That doesn't have much to do with hugo and more with html and css. The menu template would be adjusted with html, and the css would be adjusted for the new html.

**Comment by toby63** [comment]
I guess I put this on hold, until the website layout is changed.
Alternative would be to put it also in the footer in the meantime.

**Comment by Krzmbrzl** [comment]
I think putting it into the footer for the time being should be fine

**Comment by toby63** [comment]
Ok, then I will wait until #128 is merged, to add the **Source Code** Link to the footer.

**Comment by toby63** [comment]
The title is: `Mumble on GitHub`
If you prefer something else, just say.

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Krzmbrzl** [comment]
I think it's fine :+1:

**Pull request merged**
