### PR TITLE
Add "Sponsors" page

### PR DESCRIPTION
**Pull request by davidebeatrici**
Unfortunately I couldn't find Backtrace's logo in SVG.

### CODE REVIEW

**Review by Krzmbrzl — APPROVED** [review]

**Comment by Kissaki** [comment]
Do we want to differentiate between sponsors that provide otherwise paid services for free to us specifically, and those who do for open source or free software in general?

If we list Backtrace why not GitHub or Azure which also provide their service free to us as an open source project?

**Comment by Krzmbrzl** [comment]
Agreed. We should probably only list sponsors that benefit us specifically. Otherwise we had to expand the list quite a bit and it would also miss the point of such a list imo.

**Comment by davidebeatrici** [comment]
I agree. Backtrace, just like Fastly and MacStadium, offer their paid services to us for free.

**Comment by Krzmbrzl** [comment]
This seems to contradict Kissaki's statement. According to him Backtrace is free for all OpenSource projects... What is it then?

**Comment by davidebeatrici** [comment]
There's a free trial, but otherwise it's a paid service.

**Comment by Kissaki** [comment]
Then what is this https://support.backtrace.io/hc/en-us/articles/360040517031-Backtrace-for-Open-Source

> Backtrace offers our crash management platform for free to Open Source projects, subject to certain criteria and our own discretion.

**Comment by davidebeatrici** [comment]
> subject to certain criteria and our own discretion.

Which is not the case for GitHub and Azure.

**Comment by Krzmbrzl** [comment]
In that case I'd say that backtrace is not sponsoring us specifically akd should therefore not be added to the pagebin the current manner.

We could however add a section at the bottom of the page where we list services that we are using for free since we are an OpenSource project. Among others we can list backtrace there

**Pull request merged**
