### PR TITLE
Add Sur.ly's Super Convenient Voice Chat App award to the homepage

### PR DESCRIPTION
**Pull request by davidebeatrici**
https://sur.ly/i/mumble.info

We've been awarded!

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Please note that the style and colors can be chosen.

**Comment by Krzmbrzl** [comment]
I don't like the banner being placed dead center at the top. Imo this is something that should be embedded on the side somewhere.
Where it currently is, it seems to be way too attention-grabbing :thinking:

**Comment by davidebeatrici** [comment]
Feel free to make changes.

**Comment by Krzmbrzl** [comment]
I don't have the necessary HTML skills (or the time to patch them together) to get that done in a way that adapts properly to different canvas sizes :shrug:

**Comment by Kissaki** [comment]
I interpreted their email as bait.

I have never heard of this service before. Looking at their website, I do not see anything that would reasonably change this impression. They do have a bunch of stuff; software plugins, chrome addon and whatnot, but it is all anonymous author and responsibility. Nothing is verifyable.

With the possibility of this being a publicity link farm I would rather not include them unless our benefits of it are pointed out. And I definitely do not want it as a central top banner on our website. This is not a universally known and acknowledged award. For me, personally, right now, it is a non-telling, unverifiable empty award and possibly a simple bait as such.

**Comment by Kissaki** [comment]
I don’t even agree with “super convenient“. I don’t think that’s a strength of ours. Which makes me see it as another indicator this may be automated bait.

**Comment by davidebeatrici** [comment]
The email we received was in my spam folder, probably due to the wording.

According to their website the service mostly consists in a links checker, to prevent phishing and other bad stuff.

However, I would expect "Super Convenient Voice Chat App" to be referred to the project itself rather than the website.

**Comment by Kissaki** [comment]
> However, I would expect "Super Convenient Voice Chat App" to be referred to the project itself rather than the website.

I was referring to the app, not the website on that.

**Comment by ZeroAbility** [comment]
Based on a cursory examination of their website, I don't think this accolade really offers anything significant. They place a bar at the top that shows the domain that was the source of an external link, and some indicators of page safety which seem arbitrary. It would probably be free advertising for them and not much benefit to us.

**Comment by davidebeatrici** [comment]
Should we contact them and ask for a detailed explanation?

**Comment by Krzmbrzl** [comment]
To what end? I agree with ZeroAbility that it is not worth much for us and I doubt that thus would change based on their explanation :thinking:

**Pull request closed without merging**
